[package]
name = "main"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
envfury = "0.2"
grammers-client = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
